### ISSUE TITLE
Python error (Internal Servor

### ISSUE THREAD

**Issue by Thundasius** [warrieka/geopunt4Qgis#10]
While trying to open the Geopunt Catalogus I get a Phython error and I cannot search for any data without having an Internal Server error blocking my search. Al the other functions of the plugin work fine except the catologus one. I even tried a reinstall after a removal of the plugin but it does not solve the problem. Here is the Traceback:

> Traceback (most recent call last):
>   File "C:/Users/X/.qgis2/python/plugins\geopunt4Qgis\geopunt4qgis.py", line 279, in rundatacatalog
>     self.datacatalogusDlg.show()
>   File "C:/Users/X/.qgis2/python/plugins\geopunt4Qgis\geopunt4QgisDataCatalog.py", line 135, in show
>     self.bronnen = self.md.list_bronnen()
>   File "C:/Users/X/.qgis2/python/plugins\geopunt4Qgis\metadataParser.py", line 197, in list_bronnen
>     raise metaError( str( e.reason ))
> metaError: 'Internal Server Error'

**Comment by warrieka** [comment]
The server at AGIV was out probably, seems to work fine now.
