### ISSUE TITLE
bounding box of view not used for wfs layer

### ISSUE THREAD

**Issue by pjhaest** [warrieka/geopunt4Qgis#12]
Using QGIS 2.14: when loading datapoints from DOV (e.g.  wfs of "grondwatervergunningen (huidige)"), the maximal amount of 10k points is loaded, not taking into account the bounding box of the current view in QGIS. As such, not all data points of interest are taken along. Is it possible to include the bounding box of the view in the data selection?

**Comment by warrieka** [comment]
Yes, some thing's have changed since version 2.10, the version i used to develop this plugin.
If you  use the version 2.18.3 it will load the WFS in parts and only within current view, I advise using this version of QGIS.
