### ISSUE TITLE
python error catalogue geopunt plugin

### ISSUE THREAD

**Issue by dherrema** [warrieka/geopunt4Qgis#13]
Dear,

When opening using catalogue in the geopunt4Qgis plugin following error occurs:

Er is een fout opgetreden bij het uitvoeren van Python code: 

metaError: 'timed out' 
Traceback (most recent call last):
  File "C:/Users/dherrema/.qgis2/python/plugins\geopunt4Qgis\geopunt4qgis.py", line 279, in rundatacatalog
    self.datacatalogusDlg.show()
  File "C:/Users/dherrema/.qgis2/python/plugins\geopunt4Qgis\geopunt4QgisDataCatalog.py", line 131, in show
    self.ui.GDIThemaCbx.addItems([''] + self.md.list_GDI_theme())
  File "C:/Users/dherrema/.qgis2/python/plugins\geopunt4Qgis\metadataParser.py", line 131, in list_GDI_theme
    raise metaError( str( sys.exc_info()[1] ))
metaError: 'timed out'

Python versie: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS versie: 2.18.11 Las Palmas, 29548e7 

Python pad:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/dherrema/.qgis2/python
C:/Users/dherrema/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/dherrema/.qgis2//python
C:\Users\dherrema\.qgis2\python\plugins\geopunt4Qgis\ext-libs
D:/Goed in erfgoed/Ninove Burcht/GIS

**Comment by warrieka** [comment]
Do you still have this problem?
From the message I read it cannot fetch the GDI-theme keywords from the server.
I just tested it and cannot reproduce it. 
Maybe it was just a temporary problem with the web-service from the agency?

Anyway I will add code to prevent the not loading of keywords to crash the application.
