### ISSUE TITLE
links to geopunt lost

### ISSUE THREAD

**Issue by pjhaest** [warrieka/geopunt4Qgis#15]
Probably this is not code-related. But all links to the geopunt data are lost?
Using QGIS 2.14, latest geopunt4Qgis plugin.

**Comment by warrieka** [comment]
I sorry i don't understand, what is lost?

**Comment by pjhaest** [comment]
Up and running again. I think the service of Geopunt was down for some time? Would it be possible to show downtime of the service in a popup window? Or any difficultly connecting to the service (could also be on the client side).
